# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
service: rtfConverter

provider:
  name: aws
  runtime: provided
  region: eu-west-2
  stage: ${opt:stage}

functions:
  convert:
    handler: handler.convert
    layers:
      - arn:aws:lambda:${self:provider.region}:445285296882:layer:perl-5-30-runtime:8
    events:
      - http:
          path: "/"
          method: POST
  form:
    handler: handler.form
    layers:
      - arn:aws:lambda:${self:provider.region}:445285296882:layer:perl-5-30-runtime:8
    events:
      - http:
          path: "/"
          method: GET
