service: rtfConverter

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2
  stage: ${opt:stage}
  memorySize: 256
  layers:
    - arn:aws:lambda:${self:provider.region}:445285296882:layer:perl-5-30-runtime:8
    - { Ref: PerlModulesLambdaLayer }

plugins:
  - serverless-offline

package:
  exclude:
    - "Dockerfile"
    - "*.rtf"
    - "*.sh"
    - "Makefile"

layers:
  perlModules:
    path: perl_layer
    description: The libraries required to run the RTF converter

functions:
  convert:
    handler: lambda.handler
    events:
      - http:
          path: "/"
          method: ANY
